language: c

addons:
  apt:
    packages:
      - inotify-tools
      - bash

before_install:
  - sudo bash distrib/build/toolcrib/host_debian_inst

install: cd distrib/build && make predownload

script: cd distrib/build && make build
