language: c

compiler:
  - gcc
addons:
  apt:
    packages:
      - inotify-tools
      - bash
before_install:
  - sudo bash distrib/build/toolcrib/host_debian_inst
script: cd distrib/build; make build
